from .base import *  # noqa: F401,F403
from .base import ALLOWED_HOSTS, INTERNAL_TOKEN, SECRET_KEY, env
from .guards import assert_production_safe

DEBUG = False
AUTH_COOKIE_SECURE = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

assert_production_safe(SECRET_KEY, INTERNAL_TOKEN, ALLOWED_HOSTS, env("DJANGO_SUPERUSER_PASSWORD", ""))
