# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BnpDebtType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип задолженности БНП',
                'verbose_name_plural': 'Типы задолженности БНП',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BnpDocType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип документа БНП',
                'verbose_name_plural': 'Типы документов БНП',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DebtGroupScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('group', models.PositiveSmallIntegerField(unique=True, verbose_name='Группа')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('months_from', models.PositiveIntegerField(verbose_name='Месяцев от (включительно)')),
                ('months_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Месяцев до (не включительно)')),
            ],
            options={
                'verbose_name': 'Группа задолженности',
                'verbose_name_plural': 'Шкала групп задолженности',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='BnpService',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('service_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор услуги')),
                ('type_id', models.CharField(max_length=50, verbose_name='Тип (typeId)')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('debt_types', models.ManyToManyField(blank=True, related_name='services', to='nsi.bnpdebttype', verbose_name='Типы долга')),
            ],
            options={
                'verbose_name': 'Услуга БНП',
                'verbose_name_plural': 'Услуги БНП',
                'ordering': ['service_id'],
            },
        ),
    ]
