# Generated by Django 5.1.15 on 2026-09-25 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_reference(apps, schema_editor):
    ScenarioRule = apps.get_model("nsi", "ScenarioRule")
    DebtorCategory = apps.get_model("nsi", "DebtorCategory")
    CalculationSettings = apps.get_model("nsi", "CalculationSettings")
    CalculationSettings.objects.get_or_create(pk=1)
    for group, name in (
        (1, "Превентивный обзвон и уведомления"),
        (2, "Письменное предупреждение"),
        (3, "Отключение и подготовка взыскания"),
        (4, "Взыскание через ОПИ"),
        (5, "Взыскание через ОПИ"),
        (6, "Взыскание, безнадёжная задолженность"),
    ):
        ScenarioRule.objects.get_or_create(group=group, defaults={"name": name})
    for code, name, note in (
        ("pensioner", "Пенсионер", "Мягкий график уведомлений"),
        ("idler", "Не занят в экономике", "Отягчающий признак рейтинга D"),
        ("large_family", "Многодетная семья", "Ограничение отключения"),
        ("bankrupt", "Банкротство", "Отягчающий признак рейтинга D"),
    ):
        DebtorCategory.objects.get_or_create(code=code, organization=None, defaults={"name": name, "note": note})


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0001_initial'),
        ('users', '0002_user_contour'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('rating_period_months', models.PositiveIntegerField(default=12, verbose_name='Период рейтинга, мес.')),
                ('close_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Порог остатка для закрытия')),
                ('payment_due_day', models.PositiveSmallIntegerField(default=25, verbose_name='День срока оплаты')),
            ],
            options={
                'verbose_name': 'Параметры расчёта',
                'verbose_name_plural': 'Параметры расчёта',
            },
        ),
        migrations.CreateModel(
            name='ScenarioRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('group', models.PositiveSmallIntegerField(unique=True, verbose_name='Группа')),
                ('name', models.CharField(max_length=250, verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Сценарий по группе',
                'verbose_name_plural': 'Сценарии по группам',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='DebtorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Влияние на сценарии')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_categories', to='users.organization', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Категория должника',
                'verbose_name_plural': 'Категории должников',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uniq_central_debtor_category'), models.UniqueConstraint(fields=('organization', 'code'), name='uniq_debtor_category_code')],
            },
        ),
        migrations.RunPython(seed_reference, migrations.RunPython.noop),
    ]
