# Generated by Django 5.1.15 on 2026-09-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0002_calculationsettings_scenariorule_debtorcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariorule',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Сценарий по группе', 'verbose_name_plural': 'Сценарии по группам'},
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='dial_mobile_from_day',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='С этого числа месяца для обзвона только мобильный'),
        ),
        migrations.AddField(
            model_name='scenariorule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_rules', to='nsi.debtorcategory', verbose_name='Категория должника'),
        ),
        migrations.AlterField(
            model_name='scenariorule',
            name='group',
            field=models.PositiveSmallIntegerField(verbose_name='Группа'),
        ),
        migrations.AddConstraint(
            model_name='scenariorule',
            constraint=models.UniqueConstraint(fields=('group', 'category'), name='uniq_scenario_group_category', nulls_distinct=False),
        ),
    ]
