# Generated by Django 5.1.15 on 2026-09-30 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0005_measure_settings'),
        ('users', '0002_user_contour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('code', models.SlugField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('doc_kind', models.CharField(max_length=30, verbose_name='Вид документа')),
                ('body', models.TextField(verbose_name='Текст')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_forms', to='users.organization', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Печатная форма',
                'verbose_name_plural': 'Печатные формы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintFormRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('body', models.TextField(verbose_name='Текст')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='nsi.printform')),
            ],
            options={
                'verbose_name': 'Версия печатной формы',
                'verbose_name_plural': 'Версии печатных форм',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный')], default='draft', max_length=20, verbose_name='Статус')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Шаги')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='nsi.scenariodefinition', verbose_name='Источник')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='users.organization', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Сценарий мероприятий',
                'verbose_name_plural': 'Сценарии мероприятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('steps', models.JSONField(default=list, verbose_name='Шаги')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='nsi.scenariodefinition')),
            ],
            options={
                'verbose_name': 'Версия сценария',
                'verbose_name_plural': 'Версии сценария',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='printform',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_print_form_code'),
        ),
        migrations.AddConstraint(
            model_name='printform',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uniq_central_print_form'),
        ),
        migrations.AddConstraint(
            model_name='printformrevision',
            constraint=models.UniqueConstraint(fields=('form', 'version'), name='uniq_print_form_revision'),
        ),
        migrations.AddConstraint(
            model_name='scenariorevision',
            constraint=models.UniqueConstraint(fields=('scenario', 'version'), name='uniq_scenario_revision'),
        ),
    ]
