# Generated by Django 5.1.15 on 2026-10-05 11:56

import apps.nsi.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0015_cfg_425'),
        ('nsi', '0006_claims_and_scenarios'),
        ('users', '0003_cfg_425'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('version', models.PositiveIntegerField(verbose_name='Версия макета')),
                ('addressee', models.CharField(default='debtor', max_length=20, verbose_name='Адресат')),
                ('body', models.TextField(verbose_name='Текст')),
                ('batch', models.CharField(blank=True, max_length=36, verbose_name='Пакет')),
                ('file', models.FileField(upload_to='printed/%Y/%m/', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Сформированный документ',
                'verbose_name_plural': 'Сформированные документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='printform',
            name='uniq_print_form_code',
        ),
        migrations.RemoveConstraint(
            model_name='printform',
            name='uniq_central_print_form',
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='dial_mobile_weekdays',
            field=models.JSONField(blank=True, default=apps.nsi.models.weekend_days, help_text='0 — понедельник, 6 — воскресенье.', verbose_name='Дни недели только мобильного'),
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='rating_b_group',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Группа рейтинга B'),
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='rating_c_from',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Группа рейтинга C от'),
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='rating_c_to',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Группа рейтинга C по'),
        ),
        migrations.AddField(
            model_name='calculationsettings',
            name='rating_e_from',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Группа рейтинга E от'),
        ),
        migrations.AddField(
            model_name='printform',
            name='addressee',
            field=models.CharField(default='debtor', max_length=20, verbose_name='Адресат'),
        ),
        migrations.AddField(
            model_name='printform',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Размер шрифта'),
        ),
        migrations.AddField(
            model_name='printform',
            name='indent_mm',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отступ, мм'),
        ),
        migrations.AddField(
            model_name='printform',
            name='logo_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='printform',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='printform',
            name='signatory',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подпись уполномоченного'),
        ),
        migrations.AddField(
            model_name='printformrevision',
            name='layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='Макет'),
        ),
        migrations.AddField(
            model_name='scenariodefinition',
            name='call_legal',
            field=models.BooleanField(blank=True, help_text='Пусто — брать признак организации.', null=True, verbose_name='Звонить юридическим лицам'),
        ),
        migrations.AddField(
            model_name='scenariodefinition',
            name='dial_mobile_from_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='С этого числа только мобильный'),
        ),
        migrations.AddField(
            model_name='scenariodefinition',
            name='dial_mobile_weekdays',
            field=models.JSONField(blank=True, help_text='Пусто — общее правило. Числа 0–6, понедельник = 0.', null=True, verbose_name='Дни недели только мобильного'),
        ),
        migrations.AddConstraint(
            model_name='printform',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'addressee'), name='uniq_print_form_code'),
        ),
        migrations.AddConstraint(
            model_name='printform',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code', 'addressee'), name='uniq_central_print_form'),
        ),
        migrations.AddField(
            model_name='printeddocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_documents', to='debts.account', verbose_name='ЛС'),
        ),
        migrations.AddField(
            model_name='printeddocument',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='nsi.printform', verbose_name='Макет'),
        ),
    ]
