# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('schema_name', models.CharField(max_length=30, unique=True, verbose_name='Имя схемы АИС')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('unp', models.CharField(blank=True, max_length=9, verbose_name='УНП')),
            ],
            options={
                'verbose_name': 'Схема начисляющей организации',
                'verbose_name_plural': 'Схемы начисляющих организаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('provider_id', models.BigIntegerField(verbose_name='Код организации в АИС')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='Полное наименование')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Поставщик услуг')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_organizations', to='users.organization', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Обслуживающая организация',
                'verbose_name_plural': 'Обслуживающие организации',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Суперадминистратор'), ('local_admin', 'Локальный администратор'), ('specialist', 'Специалист'), ('observer', 'Наблюдатель')], default='specialist', max_length=20, verbose_name='Роль')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=250, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.organization', verbose_name='Схема')),
                ('service_organizations', models.ManyToManyField(blank=True, related_name='users', to='users.serviceorganization', verbose_name='Контур: обслуживающие организации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='serviceorganization',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_id'), name='uniq_service_org_provider'),
        ),
    ]
