# Generated by Django 5.1.15 on 2026-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contour',
            field=models.CharField(choices=[('billing', 'Начисляющая организация'), ('supplier', 'Поставщик услуг')], default='billing', help_text='Поставщик видит только услуги, где его организация назначена поставщиком', max_length=20, verbose_name='Контур'),
        ),
    ]
