# Generated by Django 5.1.15 on 2026-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_contour'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='call_legal',
            field=models.BooleanField(default=False, verbose_name='Звонить юридическим лицам'),
        ),
    ]
