# Generated by Django 5.1.15 on 2026-09-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление/деактивация'), ('view', 'Просмотр'), ('import', 'Импорт')], max_length=20, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=100, verbose_name='Объект')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='До')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='После')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='ID запроса')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='backend', max_length=50, verbose_name='Сервис')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID запроса')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Путь')),
                ('error_type', models.CharField(max_length=200, verbose_name='Тип ошибки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('traceback', models.TextField(blank=True, verbose_name='Трассировка')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Пользователь')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Журнал ошибок',
                'ordering': ['-created_at'],
            },
        ),
    ]
