# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('entity', models.CharField(choices=[('account', 'Карточка ЛС'), ('service', 'Услуги'), ('payment', 'Оплаты'), ('registration', 'Регистрация')], max_length=20, verbose_name='Тип выгрузки')),
                ('file_name', models.CharField(max_length=255, verbose_name='Файл')),
                ('checksum', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('encoding', models.CharField(blank=True, max_length=20, verbose_name='Кодировка')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('done', 'Завершён'), ('done_with_errors', 'Завершён с ошибками'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Строк')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('unchanged', models.PositiveIntegerField(default=0, verbose_name='Без изменений')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='Отклонено')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Причины отклонения')),
                ('unknown_columns', models.JSONField(blank=True, default=list, verbose_name='Колонки без сопоставления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
            ],
            options={
                'verbose_name': 'Импорт выгрузки',
                'verbose_name_plural': 'Журнал импорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
