# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
    ]
