# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0002_initial'),
        ('imports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='debts.account', verbose_name='ЛС'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.account', verbose_name='ЛС'),
        ),
        migrations.AddField(
            model_name='payment',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='registration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='debts.account', verbose_name='ЛС'),
        ),
        migrations.AddField(
            model_name='registration',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='registration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_id', 'account_id'), name='uniq_account_in_scope'),
        ),
        migrations.AddConstraint(
            model_name='accountservice',
            constraint=models.UniqueConstraint(fields=('account', 'service_list_id'), name='uniq_service_contract'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('account', 'receipt_id'), name='uniq_payment_receipt'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('account', 'registration_id'), name='uniq_registration'),
        ),
    ]
