# Generated by Django 5.1.15 on 2026-09-25 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_account_ais_updated_at_account_assigned_to_and_more'),
        ('imports', '0002_initial'),
        ('users', '0002_user_contour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payer_unp',
            field=models.CharField(blank=True, max_length=20, verbose_name='УНП'),
        ),
        migrations.AddField(
            model_name='measure',
            name='artifact',
            field=models.FileField(blank=True, upload_to='measures/%Y/%m/', verbose_name='Файл для внешней системы'),
        ),
        migrations.AddField(
            model_name='measure',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_measures', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='measure',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='measure',
            name='template_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='payer_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Идентификационный номер'),
        ),
        migrations.CreateModel(
            name='MeasureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('title', models.CharField(max_length=250, verbose_name='Задание')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('done', 'Выполнено')], default='open', max_length=20, verbose_name='Статус')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measure_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='debts.measure', verbose_name='Мероприятие')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDebtPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('period', models.DateField(verbose_name='Расчётный период')),
                ('principal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Остаток основного долга')),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Остаток пени')),
                ('due_on', models.DateField(verbose_name='Срок оплаты')),
                ('started_on', models.DateField(verbose_name='Дата возникновения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_periods', to='debts.account', verbose_name='ЛС')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_periods', to='debts.accountservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Период долга',
                'verbose_name_plural': 'Периоды долга',
                'ordering': ['period'],
                'constraints': [models.UniqueConstraint(fields=('service', 'period'), name='uniq_service_debt_period')],
            },
        ),
        migrations.CreateModel(
            name='WritCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('code', models.CharField(max_length=40, verbose_name='Код')),
                ('title', models.CharField(max_length=250, verbose_name='Пункт')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writ_checks', to='debts.account', verbose_name='ЛС')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Чек-лист исполнительной надписи',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('account', 'code'), name='uniq_writ_check')],
            },
        ),
    ]
