# Generated by Django 5.1.15 on 2026-09-29 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0009_legal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('country', 'Страна'), ('oblast', 'Область'), ('district', 'Район'), ('settlement', 'Населённый пункт'), ('microdistrict', 'Микрорайон'), ('street', 'Улица'), ('house', 'Дом')], max_length=20, verbose_name='Уровень')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('name_key', models.CharField(max_length=250, verbose_name='Ключ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='debts.territory', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='debts.territory', verbose_name='Дом в дереве адресов'),
        ),
        migrations.CreateModel(
            name='TerritoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveSmallIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='debts.territory')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='debts.territory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'kind', 'name_key'), name='uniq_territory_child'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('kind', 'name_key'), name='uniq_territory_root'),
        ),
        migrations.AddIndex(
            model_name='territorylink',
            index=models.Index(fields=['ancestor', 'depth'], name='territory_ancestor_depth'),
        ),
        migrations.AddConstraint(
            model_name='territorylink',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uniq_territory_link'),
        ),
    ]
