# Generated by Django 5.1.15 on 2026-09-29 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0010_territory'),
        ('imports', '0002_initial'),
        ('users', '0002_user_contour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='approval',
            field=models.CharField(blank=True, max_length=20, verbose_name='Решение по согласованию'),
        ),
        migrations.AddField(
            model_name='measure',
            name='approval_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий согласования'),
        ),
        migrations.AddField(
            model_name='measure',
            name='call_legal',
            field=models.BooleanField(default=False, verbose_name='Звонить юридическим лицам'),
        ),
        migrations.AddField(
            model_name='measure',
            name='group_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Группа с'),
        ),
        migrations.AddField(
            model_name='measure',
            name='group_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Группа по'),
        ),
        migrations.AddField(
            model_name='measure',
            name='needs_approval',
            field=models.BooleanField(default=False, verbose_name='Нужно согласование'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='balance_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Исходящее сальдо'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('running', 'Выполняется'), ('done', 'Завершено'), ('paused', 'Приостановлено'), ('cancelled', 'Прервано'), ('failed', 'Завершено с ошибкой')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='kind',
            field=models.CharField(choices=[('group', 'Группа'), ('rating', 'Рейтинг'), ('funnel', 'Этап воронки'), ('scenario', 'Сценарий'), ('contact', 'Контакт'), ('category', 'Категория'), ('inheritance', 'Наследственное дело'), ('registration', 'Регистрация'), ('residence', 'Проживание'), ('legal', 'Статус лица')], max_length=20, verbose_name='Вид'),
        ),
        migrations.CreateModel(
            name='MeasureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('running', 'Выполняется'), ('done', 'Завершено'), ('cancelled', 'Прервано пользователем'), ('failed', 'Завершено с ошибкой')], default='assigned', max_length=20, verbose_name='Статус')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('call_result', models.CharField(blank=True, choices=[('answered', 'Дозвон'), ('no_answer', 'Недозвон'), ('busy', 'Занято'), ('bad_number', 'Неверный номер')], max_length=20, verbose_name='Результат звонка')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, с')),
                ('listen_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Доля прослушивания, %')),
                ('recipient', models.CharField(blank=True, max_length=250, verbose_name='Адресат')),
                ('delivery_error', models.CharField(blank=True, max_length=500, verbose_name='Ошибка доставки')),
                ('notification_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оповещение')),
                ('delivery_method', models.CharField(blank=True, choices=[('personal', 'Лично под роспись'), ('registered', 'Заказное письмо'), ('administration', 'Через администрацию учреждения')], max_length=20, verbose_name='Способ вручения')),
                ('delivered_on', models.DateField(blank=True, null=True, verbose_name='Дата вручения или акта')),
                ('recipient_name', models.CharField(blank=True, max_length=250, verbose_name='ФИО получившего')),
                ('refused', models.BooleanField(default=False, verbose_name='Отказ или невручение')),
                ('postal_id', models.CharField(blank=True, max_length=50, verbose_name='Почтовый идентификатор')),
                ('postal_status', models.CharField(blank=True, max_length=50, verbose_name='Статус отправления')),
                ('suspended_on', models.DateField(blank=True, null=True, verbose_name='Дата приостановления')),
                ('resumed_on', models.DateField(blank=True, null=True, verbose_name='Дата возобновления')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда зафиксировано')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_items', to='debts.account', verbose_name='ЛС')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measure_item_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='debts.measure', verbose_name='Партия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
                ('warning_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnects', to='debts.measureitem', verbose_name='Предупреждение')),
            ],
            options={
                'verbose_name': 'Частное мероприятие',
                'verbose_name_plural': 'Частные мероприятия',
                'ordering': ['account_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeasureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Стало')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Основание')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='debts.measure', verbose_name='Партия')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='debts.measureitem', verbose_name='Частное мероприятие')),
            ],
            options={
                'verbose_name': 'Событие мероприятия',
                'verbose_name_plural': 'События мероприятий',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='measureitem',
            constraint=models.UniqueConstraint(fields=('measure', 'account'), name='uniq_measure_item'),
        ),
    ]
