# Generated by Django 5.1.15 on 2026-09-30 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0011_measure_items'),
        ('imports', '0002_initial'),
        ('users', '0002_user_contour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Акт ОПИ',
                'verbose_name_plural': 'Акты ОПИ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('decision', models.CharField(choices=[('pending', 'Ожидает'), ('yes', 'Согласовано'), ('no', 'Отказ')], default='pending', max_length=20, verbose_name='Решение')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Причина')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда решил')),
            ],
            options={
                'verbose_name': 'Согласование списания',
                'verbose_name_plural': 'Согласования списания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('stage', models.CharField(choices=[('prep', 'Подготовка пакета'), ('notary', 'Направлено нотариусу'), ('writ_done', 'Надпись совершена'), ('refused', 'Отказ нотариуса'), ('lawsuit', 'Исковое заявление'), ('court', 'Судебное решение'), ('opi', 'Направлено в ОПИ'), ('opi_measures', 'Меры ОПИ'), ('recovered', 'Взыскано'), ('impossible', 'Невозможность взыскания'), ('writeoff', 'Списание')], db_index=True, default='prep', max_length=20, verbose_name='Этап')),
                ('warning_delivered_on', models.DateField(blank=True, null=True, verbose_name='Дата вручения предупреждения')),
                ('notary_tariff', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Нотариальный тариф')),
                ('application_withdrawn', models.BooleanField(default=False, verbose_name='Заявление отозвано')),
                ('submission_id', models.CharField(blank=True, max_length=64, verbose_name='Номер обращения')),
                ('submission_mode', models.CharField(blank=True, max_length=20, verbose_name='Канал отправки')),
                ('notary_note', models.CharField(blank=True, max_length=500, verbose_name='Ответ нотариуса')),
                ('lawsuit_number', models.CharField(blank=True, max_length=50, verbose_name='Номер иска')),
                ('lawsuit_kind', models.CharField(blank=True, choices=[('collection', 'Взыскание задолженности'), ('eviction_80', 'Выселение, ст. 80 ЖК'), ('eviction_86', 'Выселение, ст. 86 ЖК'), ('eviction_87', 'Выселение, ст. 87 ЖК'), ('alienation_137', 'Отчуждение, ст. 137 ЖК')], max_length=20, verbose_name='Вид иска')),
                ('lawsuit_filed_on', models.DateField(blank=True, null=True, verbose_name='Дата подачи иска')),
                ('state_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Госпошлина')),
                ('defendant_name', models.CharField(blank=True, max_length=250, verbose_name='Ответчик')),
                ('package_filed_on', models.DateField(blank=True, null=True, verbose_name='Дата подачи пакета документов')),
                ('lawsuit_note', models.CharField(blank=True, max_length=500, verbose_name='Примечание к иску')),
                ('court_status', models.CharField(blank=True, choices=[('', 'Не подано'), ('pending', 'На рассмотрении'), ('granted', 'Удовлетворено'), ('denied', 'Отказано в иске')], max_length=20, verbose_name='Статус суда')),
                ('opi_number', models.CharField(blank=True, max_length=50, verbose_name='Номер производства ОПИ')),
                ('opi_status', models.CharField(blank=True, max_length=40, verbose_name='Статус ОПИ')),
                ('opi_mode', models.CharField(blank=True, max_length=20, verbose_name='Канал ОПИ')),
                ('tariff_received', models.BooleanField(default=False, verbose_name='Тариф поступил по выгрузке')),
                ('ais_debt_cleared', models.BooleanField(default=False, verbose_name='Выгрузка показала погашение долга и пени')),
                ('eviction_stage', models.CharField(blank=True, max_length=20, verbose_name='Параллельная ветвь выселения')),
                ('skip_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина пропуска этапа')),
                ('writeoff_status', models.CharField(blank=True, choices=[('', 'Не запускалось'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отказ согласующего')], max_length=20, verbose_name='Согласование списания')),
                ('writeoff_note', models.CharField(blank=True, max_length=500, verbose_name='Итог списания')),
            ],
            options={
                'verbose_name': 'Дело взыскания',
                'verbose_name_plural': 'Дела взыскания',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('old_stage', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_stage', models.CharField(blank=True, max_length=20, verbose_name='Стало')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Основание')),
            ],
            options={
                'verbose_name': 'Событие дела',
                'verbose_name_plural': 'События дела',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('paused', models.BooleanField(default=False, verbose_name='Приостановлен')),
                ('pause_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина приостановки')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_run', to='debts.account', verbose_name='ЛС')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Запуск сценария',
                'verbose_name_plural': 'Запуски сценариев',
            },
        ),
    ]
