# Generated by Django 5.1.15 on 2026-09-30 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0012_claims_and_scenarios'),
        ('imports', '0002_initial'),
        ('nsi', '0006_claims_and_scenarios'),
        ('users', '0002_user_contour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscenariorun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='nsi.scenariodefinition', verbose_name='Сценарий'),
        ),
        migrations.AddField(
            model_name='claimact',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='claimact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='claimcase',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_case', to='debts.account', verbose_name='ЛС'),
        ),
        migrations.AddField(
            model_name='claimcase',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='claimcase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='debts.claimcase', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='claimact',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='debts.claimcase', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='claimevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто'),
        ),
        migrations.AddField(
            model_name='claimevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='debts.claimcase', verbose_name='Дело'),
        ),
        migrations.AddConstraint(
            model_name='claimapproval',
            constraint=models.UniqueConstraint(fields=('case', 'approver'), name='uniq_claim_approver'),
        ),
    ]
