# Generated by Django 5.1.15 on 2026-10-05 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0014_debt_shares_and_measure_owner'),
        ('nsi', '0006_claims_and_scenarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscenariorun',
            name='last_skip',
            field=models.CharField(blank=True, max_length=300, verbose_name='Почему шаг не стартовал'),
        ),
        migrations.AddField(
            model_name='accountscenariorun',
            name='skipped_orders',
            field=models.JSONField(blank=True, default=list, verbose_name='Пропущенные шаги'),
        ),
        migrations.AddField(
            model_name='measure',
            name='auto_complete',
            field=models.BooleanField(default=False, verbose_name='Закрыть после отправки'),
        ),
        migrations.AddField(
            model_name='measure',
            name='source_action',
            field=models.CharField(blank=True, max_length=30, verbose_name='Действие шага'),
        ),
        migrations.AddField(
            model_name='measure',
            name='source_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='nsi.scenariodefinition', verbose_name='Сценарий-источник'),
        ),
        migrations.AddField(
            model_name='measure',
            name='source_step',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Шаг сценария'),
        ),
        migrations.AddField(
            model_name='measure',
            name='source_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Версия сценария'),
        ),
        migrations.CreateModel(
            name='ScenarioPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('paused', models.BooleanField(verbose_name='Пауза')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Причина')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='debts.accountscenariorun', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Пауза сценария',
                'verbose_name_plural': 'Паузы сценария',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
