# Generated by Django 5.1.15 on 2026-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0016_saved_filter_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='spent_fact',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True, verbose_name='Начислено (количество)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='tarrif',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True, verbose_name='Тариф'),
        ),
    ]
