# Generated by Django 5.1.15 on 2026-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0017_service_decimal_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_category_full',
            field=models.CharField(blank=True, max_length=250, verbose_name='Полное наименование (типа объекта лс)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id типа объекта лс'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_category_short',
            field=models.CharField(blank=True, max_length=50, verbose_name='Краткое наименование (типа объекта лс)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_total_space',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая площадь ЛС (Площадь)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_address',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Адрес ЛС запросом (Адрес)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.BigIntegerField(verbose_name='Код ЛС'),
        ),
        migrations.AlterField(
            model_name='account',
            name='calc_result_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Субсидия (сумма субсидии)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование категории жилого фонда (категория жилого фонда)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category_short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Краткое наименование категории жилого фонда'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client_account',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Лицевой счёт (Номер ЛС)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_private_enterprise',
            field=models.BooleanField(default=False, verbose_name='Наличие ЧУП (0 – нет, 1 – есть) (ЧУП)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ownership_type_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование типа собственности (тип собственности)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pay_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Распределенная оплата'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pay_sum_writeoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='В т.ч. Списано (списание задолженности)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='payer_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Идентификационный номер паспорта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='payer_unp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Учетный номер плательщика'),
        ),
        migrations.AlterField(
            model_name='account',
            name='priv_acc_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во льготников (Льготники)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider_short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое наименование поставщика или обслуживающей организации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='schema_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Код схемы'),
        ),
        migrations.AlterField(
            model_name='account',
            name='short_fio',
            field=models.CharField(blank=True, max_length=250, verbose_name='ФИО плательщиков (краткое) (Плательщик ФИО)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата открытия ЛС (Период действия)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия ЛС (Период действия)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subj_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во человек (всех) (Проживающие)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='unified_account',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Уникальный единый номер ЛС (УЕН ЛС)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uniq_attr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID признака уникальности ЛС'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uniq_attr_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование типа уникальности'),
        ),
        migrations.AlterField(
            model_name='account',
            name='unshared_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Нераспределённый остаток оплаты в текущем периоде (Нерасп. остаток оплаты)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='balance_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Исходящее сальдо с пенями'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='calc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата выполнения расчета (Дата расчёта)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='calculation_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Код операции расчета (ID Расчёта)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='debt_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во периодов долга'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Полное наименование поставщика'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='mulct_recalc_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Перерасчет по пене'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='netting_mulct_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Взаимозачет пени'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='netting_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Взаимозачет по услуге'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='provider_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Код поставщика услуги'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='service_id',
            field=models.BigIntegerField(verbose_name='Код услуги (ID Услуги)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='service_list_id',
            field=models.BigIntegerField(verbose_name='Код договора на услугу (ID Договора)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='service_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование услуги'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='service_name_report',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование услуги в извещении для дополнительных'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='share_mulct_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Распределённая оплата пени в текущем опер. периоде'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='share_service_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Распределённая оплата услуг в текущем опер. периоде'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='shot_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое наименование поставщика'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия услуги (Дата с)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия услуги (Дата по)'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='subs_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Субсидия (сумма субсидии)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_address',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_provider_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='обсл. организация ЛС - ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Банк - ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк - Наименование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_account_file',
            field=models.CharField(blank=True, max_length=25, verbose_name='Лицевой счет из файла'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма комиссии расчетного агента'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_mulct_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Оплата пени по квитанции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_service_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Оплата услуг по квитанции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_reg_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Поставщик услуг - ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='обсл. организация ЛС - Наименование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Услуга - ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Услуга - Наименование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='share_mulct_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Распределенная оплата пени в текущем периоде'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='share_service_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Распределенная оплата услуг в текущем периоде'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='share_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Способ распределения'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации по паспорту'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='idler_val',
            field=models.BooleanField(default=False, verbose_name='Незанятые в экономике'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_close_relative',
            field=models.BooleanField(default=False, verbose_name='Является членом семьи плательщика'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='legacy_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала открытия наследства'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='legacy_stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания открытия наследства'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='maindoc_type_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Основной документ (краткое)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payer_type_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование типа плательщика'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='personal_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Идентификационный номер паспорта'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='relation_degree_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование степени родства'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='social_category',
            field=models.CharField(blank=True, max_length=250, verbose_name='Социальная категория граждан'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='subj_legal_entity',
            field=models.BooleanField(default=False, verbose_name='Является юридическим лицом'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='work_place_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование предприятия'),
        ),
    ]
