# Generated by Django 5.1.15 on 2026-10-09 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0019_task_check'),
        ('imports', '0002_initial'),
        ('users', '0004_org_waits_and_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('service_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Услуга БНП')),
                ('contact_data', models.CharField(blank=True, max_length=500, verbose_name='Контактные данные')),
                ('notification_email', models.CharField(blank=True, max_length=250, verbose_name='E-mail для уведомлений')),
                ('user_message', models.CharField(blank=True, max_length=2000, verbose_name='Сообщение нотариусу')),
                ('debtors', models.JSONField(blank=True, default=list, verbose_name='Должники')),
                ('debts', models.JSONField(blank=True, default=list, verbose_name='Задолженность')),
                ('manifest', models.JSONField(blank=True, default=dict, verbose_name='Манифест')),
                ('problems', models.JSONField(blank=True, default=list, verbose_name='Замечания сборки')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Пакет сформирован')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='debts.claimcase', verbose_name='Дело')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Пакет БНП',
                'verbose_name_plural': 'Пакеты БНП',
            },
        ),
        migrations.CreateModel(
            name='ClaimPackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Исходная строка выгрузки')),
                ('doc_type', models.CharField(max_length=50, verbose_name='Тип документа БНП')),
                ('file_name', models.CharField(max_length=180, verbose_name='Имя PDF')),
                ('signature_name', models.CharField(max_length=190, verbose_name='Имя файла ЭЦП')),
                ('signer', models.CharField(default='applicant', max_length=20, verbose_name='Кто подписывает')),
                ('generated', models.BooleanField(default=False, verbose_name='Собран в ПМ')),
                ('pdf', models.FileField(blank=True, upload_to='claims/bnp/%Y/%m/', verbose_name='PDF')),
                ('signature', models.FileField(blank=True, upload_to='claims/bnp/%Y/%m/', verbose_name='ЭЦП')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.importjob', verbose_name='Импорт')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.organization', verbose_name='Организация')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='debts.claimpackage', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Документ пакета БНП',
                'verbose_name_plural': 'Документы пакета БНП',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('package', 'file_name'), name='uniq_bnp_package_file')],
            },
        ),
    ]
