# Generated by Django 5.1.15 on 2026-09-24 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирована')),
                ('code', models.SlugField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('channel', models.CharField(choices=[('inbox', 'Панель уведомлений ПМ'), ('email', 'E-mail'), ('sms', 'SMS'), ('voice', 'Голосовой звонок')], max_length=10, verbose_name='Канал')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='Тема (e-mail)')),
                ('body', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('channel', models.CharField(choices=[('inbox', 'Панель уведомлений ПМ'), ('email', 'E-mail'), ('sms', 'SMS'), ('voice', 'Голосовой звонок')], max_length=10, verbose_name='Канал')),
                ('body', models.TextField(blank=True, verbose_name='Текст (если без шаблона)')),
                ('recipient_name', models.CharField(blank=True, max_length=250, verbose_name='Обращение к получателю')),
                ('recipient_address', models.CharField(blank=True, max_length=250, verbose_name='Адрес (e-mail/телефон)')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Переменные шаблона')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('queued', 'Передано в шлюз'), ('sent', 'Доставлено'), ('failed', 'Ошибка')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('gateway_id', models.CharField(blank=True, max_length=64, verbose_name='ID в шлюзе')),
                ('rendered_text', models.TextField(blank=True, verbose_name='Итоговый текст')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='ID запроса')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
            },
        ),
    ]
