# Generated by Django 5.1.15 on 2026-10-05 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_open_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Версия шаблона'),
        ),
        migrations.CreateModel(
            name='MessageTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Изменено')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notifications.messagetemplate')),
            ],
            options={
                'verbose_name': 'Версия шаблона сообщения',
                'verbose_name_plural': 'Версии шаблонов сообщений',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='uniq_message_template_revision')],
            },
        ),
    ]
